//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laCasaDeRoma
{
    using System;
    using System.Collections.Generic;
    
    public partial class CadastroClientes
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cidade { get; set; }
        public string rua { get; set; }
        public string numero { get; set; }
        public string telefone { get; set; }
    }
}
