//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laCasaDeRoma
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalhePedidoMesa
    {
        public int id { get; set; }
        public string Numero_Mesa { get; set; }
        public string Quantidade_Clientes { get; set; }
        public string Obs_Pedido { get; set; }
        public string Lanche { get; set; }
        public string Bebida { get; set; }
        public double Valor_Total { get; set; }
    }
}
