//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laCasaDeRoma
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lacasa_romaEntities1 : DbContext
    {
        public lacasa_romaEntities1()
            : base("name=lacasa_romaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CadastroClientes> CadastroClientes { get; set; }
        public virtual DbSet<CadastroEntregadores> CadastroEntregadores { get; set; }
        public virtual DbSet<CadastroLanche> CadastroLanche { get; set; }
        public virtual DbSet<cadastroUsuario> cadastroUsuario { get; set; }
        public virtual DbSet<Ingredientess> Ingredientess { get; set; }
        public virtual DbSet<CadastroBebida> CadastroBebida { get; set; }
        public virtual DbSet<mesas> mesas { get; set; }
        public virtual DbSet<CadastroMesass> CadastroMesass { get; set; }
        public virtual DbSet<PedidosMesas> PedidosMesas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SomarPedidos> SomarPedidos { get; set; }
        public virtual DbSet<DetalhePedidoMesa> DetalhePedidoMesa { get; set; }
    }
}
