//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laCasaDeRoma
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosMesas
    {
        public int id { get; set; }
        public int Numero_Mesa { get; set; }
        public int Quantidade_Clientes { get; set; }
        public string Lanches_Mesa { get; set; }
        public string bebidas_Mesa { get; set; }
    }
}
